name: Do Something That Needs Scheduled
on:
  repository_dispatch:
    types: do-something


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hello World
        run: echo Hello, world!
